# Generated by Django 5.2.15 on 2026-06-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=20)),
                ('tamanio', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Disponible', max_length=50)),
            ],
        ),
    ]
